version: '3.8'

services:
  wake-on-lan:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - wol_data:/data
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - default

volumes:
  wol_data:
    driver: local

networks:
  default:
    driver: bridge
