services:
  wake-on-lan:
    build: .
    network_mode: host
    volumes:
      - wol_data:/data
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  wol_data:
    driver: local
